language: node_js
node_js:
  - 12

  env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings_tests

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  greetings_tests;' -U postgres
  - psql -U postgres -d greetings_tests -a -f tables.sql

services:
  - postgresql